name: Deploy LavMultimediaAPI to Azure

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código-fonte
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependências
        run: dotnet restore LavMultimediaAPI/LavMultimediaAPI.csproj

      - name: Build aplicação
        run: dotnet build LavMultimediaAPI/LavMultimediaAPI.csproj --configuration Release

      - name: Publish aplicação
        run: dotnet publish LavMultimediaAPI/LavMultimediaAPI.csproj -c Release -o publish

      - name: Deploy para Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: lavmultimediaapp-fja7hnetadhyb2b5
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: publish
