name: Build and deploy ASP.Net Core app to Azure Web App - lavmultimediaapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore LavMultimediaAPI/LavMultimediaAPI.csproj

      - name: Build
        run: dotnet build LavMultimediaAPI/LavMultimediaAPI.csproj --configuration Release

      - name: Publish
        run: dotnet publish LavMultimediaAPI/LavMultimediaAPI.csproj -c Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C7ED99141E7C4B9C8ED523EEC178EACB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DFF96671980443B7AC709BD6604DDFC5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F205EDEA791540E8A83A6C5715CABC88 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'lavmultimediaapp'
          slot-name: 'Production'
          package: .
