name: Build and deploy ASP.Net Core app to Azure Web App - lavmultimediaapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restaurar pacotes NuGet
        run: dotnet restore LavMultimediaAPI.csproj

      - name: Build do projeto
        run: dotnet build LavMultimediaAPI.csproj --configuration Release --no-restore

      - name: Publicar projeto
        run: dotnet publish LavMultimediaAPI.csproj -c Release -o ./publish --no-restore

      - name: Upload dos artefatos
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Baixar artefatos da etapa de build
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: ./publish

      - name: Login no Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C7ED99141E7C4B9C8ED523EEC178EACB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DFF96671980443B7AC709BD6604DDFC5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F205EDEA791540E8A83A6C5715CABC88 }}

      - name: Deploy para Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'lavmultimediaapp'
          slot-name: 'Production'
          package: ./publish
